version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
      

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install awscli
      #- run:
         # name: Git clone
         # command: git clone https://github.com/devsathyaops/ec2repo.git
      - run:
          name: Show working directory
          command: echo "Working directory is $CIRCLE_WORKING_DIRECTORY"
      - run:
          name: Upload to S3
          command: |
            aws s3 cp --recursive . s3://gitrepotobeuploaded/

     # - store_artifacts:
     #     path: /tmp
     #     destination: artifacts

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

environment:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY